name: Archive

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Notes'
        default: ''
        required: false

env:
  AWS_ID: ${{ secrets.AWS_ID }}
  AWS_KEY: ${{ secrets.AWS_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: AWS_ID=$AWS_ID AWS_KEY=$AWS_KEY AWS_REG=us-east-1 NEXT_PUBLIC_NODE_ENV=production node backend/archive/exec.js
    
