name: Archive

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Notes'
        default: ''
        required: false

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: aws s3 rm s3://writey-drawey-archive --recursive
    - run: npm install
    - run: NEXT_PUBLIC_NODE_ENV=production node backend/archive/exec.js
    
